#!/bin/sh

case "$1" in
        start)
                echo "Starting Network"
		ifup eth0
		sleep 2
		echo "Starting Camera App"
                cd /root
                python3 app.py &
                ;;
        stop)
                echo "Stopping Camera App"
                killall python3
                ;;
        restart)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "Usage (start | stop | restart)"
                exit 1
        ;;
esac
exit 0
